[manifest]
version = "1.0.0"
dump_lua = true
priority = 5

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
if scoring_hand and SMODS.has_enhancement(card, 'm_glass') and not card.debuff and pseudorandom('glass') < G.GAME.probabilities.normal/(card.ability.name == 'Glass Card' and card.ability.extra or G.P_CENTERS.m_glass.config.extra) then
    destroyed = true
end
'''
position = 'at'
match_indent = true
payload = '''
        if scoring_hand and SMODS.has_enhancement(card, 'm_glass') and not card.debuff and pseudorandom('glass') < G.GAME.probabilities.normal/(card.ability.name == 'Glass Card' and card.ability.extra or G.P_CENTERS.m_glass.config.extra) then
            if (next(SMODS.find_card("Unrivaled_fantastic_four"))) then
                card:juice_up(0.5, 0.5)
                card_eval_status_text(card, 'extra', nil, nil, nil, {message = "Shields Up!", G.C.CHIPS})
                destroyed = false
            end

            if not (next(SMODS.find_card("Unrivaled_fantastic_four"))) then
            destroyed = true
            end
        end
'''