[manifest]
version = "1.0.0"
dump_lua = true
priority = 5

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
if destroyed then
    card.getting_sliced = true
    if SMODS.shatters(card) then
        card.shattered = true
    else
        card.destroyed = true
    end
    cards_destroyed[#cards_destroyed+1] = card
end
'''
position = 'at'
match_indent = true
payload = '''
if destroyed then
    if SMODS.has_enhancement(card, 'm_glass') and (next(SMODS.find_card("j_Unrivaled_fantastic_four"))) and #context.full_hand == 4 and card:get_id() == 4 then
        card_eval_status_text(card, 'extra', nil, nil, nil, {message = "Protected!", G.C.CHIPS})
        destroyed = false
        SMODS.calculate_context({Unrivaled_protected = true})
    else
        card.getting_sliced = true
        if SMODS.shatters(card) then
            card.shattered = true
        else
            card.destroyed = true
        end
        cards_destroyed[#cards_destroyed+1] = card
    end
end
'''