[manifest]
version = "1.0.0"
dump_lua = true
priority = 5

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "if G.blind_select then"
position = "before"
payload = '''
G.GAME.current_round.usesavedtext = false
G.GAME.current_round.savedtext = ""
'''
match_indent = true

[[patches]]
[patches.regex]
target = "functions/common_events.lua"
pattern = '''localize\('ph_mr_bones'\)'''
position = 'before'
line_prepend = ''
payload = '''(G.GAME.current_round.usesavedtext and G.GAME.current_round.savedtext or '''

[[patches]]
[patches.regex]
target = "functions/common_events.lua"
pattern = '''localize\('ph_mr_bones'\)'''
position = 'after'
line_prepend = ''
payload = ''')'''